### PR TITLE
gitattributes file managment ( enforcing correct line endings )

### PR DESCRIPTION
**Pull request by mrhut10**
* enforcing unix line endings for text files
* documenting a process how to fix your local repo if this causes problems.
* enforcing binary file for true type font .ttf files

### CODE REVIEW

**Review by Irev-Dev — APPROVED** [review]
Comments could be more concise

**Comment by mrhut10** [comment]
You can also join my three commits into one commit on this parent

**Comment by Irev-Dev** [comment]
I only got notified that you replied here through email, are there not notifications here in github?

**Comment by mrhut10** [comment]
@irevdev you will need to star the project from memory to get notifications

**Pull request merged**
